apiVersion: apps/v1
kind: Deployment
metadata:
  name: ledgerapp
  labels:
    app: ledgerapp
spec:
  replicas: 3
  selector:
    matchLabels:
      app: ledgerapp
  template:
    metadata:
      labels:
        app: ledgerapp
    spec:
      containers:
        - name: ledgerapp
          image: ghcr.io/prasad3936/ledgernew:sha-1f0587533233ee8aede742b422378dc37327656f
          imagePullPolicy: Always
          ports:
            - containerPort: 5000
          resources:
            limits:
              cpu: "0.5"
              memory: "512Mi"
            requests:
              cpu: "0.2"
              memory: "256Mi"
          livenessProbe:
            httpGet:
              path: /
              port: 5000
            initialDelaySeconds: 30
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /
              port: 5000
            initialDelaySeconds: 5
            periodSeconds: 5
      imagePullSecrets:
        - name: github-container-registry
