apiVersion: v1
kind: Service
metadata:
  name: ledgerapp
  labels:
    app: ledgerapp
spec:
  type: ClusterIP
  ports:
    - port: 80
      targetPort: 5000  # Updated to match Gunicorn's port
      protocol: TCP
      name: http
  selector:
    app: ledgerapp
